### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by boscacci** [tikapi-io/tiktok-api#2]
Hello,

I am getting the following response at the `/user/info` endpoint upon following the [video tutorial](https://www.youtube.com/watch?v=JDupJKZ0Yy8&ab_channel=TikApi) in postman (I imported the TikAPI 2.1 collection):

```
{
    "message": "Captcha error from TikTok",
    "status": "error"
}
```

I have my `apiKey` and `accountKey` variables set properly.

**Comment by el1s7** [comment]
This repository is not for support, please reach us out through email or live chat
